/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    IEpAddLocation: (typeof import('~icons/ep/add-location'))['default']
    IEpAim: (typeof import('~icons/ep/aim'))['default']
  }
}
